<a href="https://colab.research.google.com/github/TamirPalay/DI_Exercises/blob/main/week14/day1-2/NLP_vectorization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

VECTORIZATION

Bag of words (BoW)

In [ ]:
import nltk
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords
import spacy

In [ ]:
from collections import Counter

# Download necessary NLTK resources if not already downloaded
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab') # Download the punkt_tab resource

doc = 'Why, sometimes I`ve believed as many as 6 impossible things before breakfast. There goes the shawl again!'
tokens = word_tokenize(doc)

stemmer = PorterStemmer()
stemmed = [stemmer.stem(word) for word in tokens]
filtered_words = [word for word in tokens if not word.lower() in stopwords.words('english')]

bow = Counter(filtered_words)
print(bow)

Counter({',': 1, 'sometimes': 1, '`': 1, 'believed': 1, 'many': 1, '6': 1, 'impossible': 1, 'things': 1, 'breakfast': 1, '.': 1, 'goes': 1, 'shawl': 1, '!': 1})


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


CounterVectorizer

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

docs = ['This is the first document.','This document is the second document.','And this is the third one.', 'This one is the 4th']

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(docs)

print("Feature names:", vectorizer.get_feature_names_out())
print("Vectorized representation:\n", X.toarray())

Feature names: ['4th' 'and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']
Vectorized representation:
 [[0 0 1 1 1 0 0 1 0 1]
 [0 0 2 0 1 0 1 1 0 1]
 [0 1 0 0 1 1 0 1 1 1]
 [1 0 0 0 1 1 0 1 0 1]]


TF-IDF (Term Frequency-Inverse Document Frequency)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Step 1: Load the Documents
documents = [
    "I love reading books.",
    "Reading in the morning is refreshing.",
    "I love morning coffee."
]

# Step 2: Apply TF-IDF Vectorization
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(documents)

# Step 3: Analyze the Output
# Print the vocabulary (unique words)
print("Vocabulary:", vectorizer.get_feature_names_out())

# Print the TF-IDF values for each document
print("TF-IDF Matrix:")
print(tfidf_matrix.toarray())

Vocabulary: ['books' 'coffee' 'in' 'is' 'love' 'morning' 'reading' 'refreshing' 'the']
TF-IDF Matrix:
[[0.68091856 0.         0.         0.         0.51785612 0.
  0.51785612 0.         0.        ]
 [0.         0.         0.44036207 0.44036207 0.         0.3349067
  0.3349067  0.44036207 0.44036207]
 [0.         0.68091856 0.         0.         0.51785612 0.51785612
  0.         0.         0.        ]]


EXERCISE 1

In [ ]:
import json
from sklearn.feature_extraction.text import TfidfVectorizer
from google.colab import files
uploaded = files.upload() #ADDED TO UPLOAD THE JSON FILE TO GOOGLE COLAB


with open('famous_poems.json', 'r') as f:
    data = json.load(f)

processed_poems = []
#cleaning stopwords
for poem in data:
    tokens = word_tokenize(poem['text'])
    filtered_tokens = [word for word in tokens if not word.lower() in stopwords.words('english') and word.isalpha()]
    processed_poems.append(' '.join(filtered_tokens))

#Applying TF-IDF
#your code here:

vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(processed_poems)

#bonus:
# Find the most important word and print
feature_names = vectorizer.get_feature_names_out()
for i, row in enumerate(tfidf_matrix.toarray()):
    max_index = row.argmax()
    most_important_word = feature_names[max_index]
    print(f"Most important word in poem '{data[i]['title']}': {most_important_word}")

Saving famous_poems.json to famous_poems (1).json
Most important word in poem 'The Road Not Taken': difference
Most important word in poem 'Still I Rise': may
Most important word in poem 'If': blaming


Word2Vec

In [ ]:
pip install nltk gensim

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 2.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 73.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 92.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 14.2 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.15.3
    Uninstalling scipy-1.15.3:
      Successfully uninstalled scipy-1.15.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tsfresh 0.21.0 requires scipy>=1.14.0; python_version >= "3.10", but you have scipy 1.13.1 which is incompatible.
thinc 8.3.6 req

In [ ]:
import nltk
from nltk.tokenize import word_tokenize
from gensim.models import Word2Vec
import gensim.downloader as api
nltk.download('punkt')

dataset = api.load("text8")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


[==================================================] 100.0% 31.6/31.6MB downloaded


In [ ]:
model = Word2Vec(sentences=dataset, vector_size=100, window=5, min_count=1, workers=4)

In [ ]:
example_result = model.wv.most_similar(positive=['woman', 'king'], negative=['savory'], topn=1)
print(example_result)

[('queen', 0.6011894941329956)]
